### PR TITLE
rename "flash" button to "connect"

### PR DESCRIPTION
**Pull request by justinotherguy**
...coming straight from "flashing" to the firmware to the controller board, I thought there might actually be an option to "flash" new firmware to the board when I saw this button. Renaming the button would minimize confusion.

### CODE REVIEW

**Comment by Candas1** [comment]
Hi, this is actually the name of the icon I used from ionicons that looked closest to what I needed. Changing the name with break the button icon.

**Comment by justinotherguy** [comment]
Hm - isn't https://github.com/Candas1/Hoverboard-Web-Serial-Control/blob/master/js/serial.js#L81 where the icon is selected?

**Comment by Candas1** [comment]
There I am changing the icon based on connection status

**Comment by justinotherguy** [comment]
Oh, I see; well - thanks for the explanation, I'll close this one, so.

**Pull request closed without merging**
